<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * The RobotClock database this app owns, not this application's own
     * default connection.
     */
    protected $connection = 'supabase';

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (app()->environment('testing') || Schema::hasTable('punches')) {
            return;
        }

        Schema::create('punches', function (Blueprint $table) {
            $table->uuid('id')->primary();
            // Deliberately no FK to cards: an unrecognized card must still be
            // recordable, so a punch isn't lost to a data-entry gap.
            $table->text('card_uid');
            $table->foreignUuid('user_id')->nullable()->constrained('users')->nullOnDelete();
            $table->text('direction');
            $table->timestampTz('punched_at');
            $table->timestampTz('recorded_at')->useCurrent();
            $table->foreignUuid('organization_id')->constrained('organizations')->restrictOnDelete();
        });

        DB::statement(<<<'SQL'
            alter table punches
                add constraint punches_direction_check check (direction in ('in', 'out'))
            SQL);

        DB::statement('create index punches_user_punched_at_idx on punches (user_id, punched_at desc)');
        DB::statement('create index punches_card_uid_punched_at_idx on punches (card_uid, punched_at desc)');
        DB::statement('create index punches_org_punched_at_idx on punches (organization_id, punched_at desc)');

        DB::statement(<<<'SQL'
            comment on column punches.id is
                'Generated by the client, not the database. Sync is an upsert on this id.'
            SQL);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        if (app()->environment('testing')) {
            return;
        }

        Schema::dropIfExists('punches');
    }
};
