<?php

namespace App\Models;

use Database\Factories\PunchFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * A clock in/out event. `id` is generated by the recording client (kiosk),
 * not the database, so syncing is an upsert on that id.
 *
 * @property string $id
 * @property string $card_uid
 * @property string|null $user_id
 * @property string $direction
 * @property Carbon $punched_at
 * @property Carbon $recorded_at
 * @property string $organization_id
 */
#[Fillable(['id', 'card_uid', 'user_id', 'direction', 'punched_at', 'organization_id'])]
class Punch extends Model
{
    /** @use HasFactory<PunchFactory> */
    use HasFactory, HasUuids;

    protected $connection = 'supabase';

    public $timestamps = false;

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'punched_at' => 'datetime',
            'recorded_at' => 'datetime',
        ];
    }

    /**
     * @return BelongsTo<User, $this>
     */
    public function employee(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * @return BelongsTo<Organization, $this>
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }
}
